name: Dispatch Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-fork:
    if: github.repository_owner == 'subject-test-33'
    runs-on: ubuntu-latest

    steps:
      - name: Echo message
        run: echo "main branch pushed"
